<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <title>ERROR 403</title>
    <meta name="description" content="Responsive, Bootstrap, BS4" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- for ios 7 style, multi-resolution icon of 152x152 -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
    <link rel="apple-touch-icon" href="/app/files/images/logo.png">
    <meta name="apple-mobile-web-app-title" content="Flatkit">
    <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" sizes="196x196" href="/app/files/images/logo.png">

    <!-- style -->
    <link rel="stylesheet" href="/app/files/plugins/bootstrap/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="/app/files/css/style.css" type="text/css" />
    <link rel="stylesheet" href="/app/files/css/font.css" type="text/css" />
    <link rel="stylesheet" href="/app/files/css/app.css" type="text/css" />
    <link rel="stylesheet" href="/app/files/css/animate.min.css" type="text/css" />
</head>
<body>
<div class="app" id="app">

    <div class="p-a black">
        <div class="navbar" data-pjax>
            <a data-toggle="collapse" data-target="#navbar" class="navbar-item pull-right hidden-md-up m-a-0 m-l">
                <i class="ion-android-menu"></i>
            </a>
            <a href="/html" class="navbar-brand">
                <span class="hidden-folded inline">ERROR</span>
            </a>
        </div>
    </div>

    <div id="content" class="app-content" role="main">
        <div class="app-body">
            <div class="row-col amber h-v">
                <div class="row-cell v-m">
                    <div class="text-center col-sm-6 offset-sm-3 p-y-lg">
                        <h1 class="display-3 m-y-lg">Acesso Restrito.</h1>
                        <p class="m-y text-muted h4">
                            -- 403 --
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
