<!DOCTYPE html>
<html>
<head>

    <!-- Title -->
    <title>VEX - ERRO 404</title>

    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta charset="UTF-8">
    <meta name="author" content="WebDatasoft" />

    <!-- Styles -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
    <link href="/app/files/css/pace-theme-flash.css" rel="stylesheet"/>
    <link href="/app/files/css/uniform.default.min.css" rel="stylesheet"/>
    <link href="/app/files/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/plugins/fontawesome/css/font-awesome.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/plugins/line-icons/simple-line-icons.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/plugins/offcanvasmenueffects/css/menu_cornerbox.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/plugins/waves/waves.min.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/plugins/switchery/switchery.min.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/plugins/3d-bold-navigation/css/style.css" rel="stylesheet" type="text/css"/>

    <!-- Theme Styles -->
    <link href="/app/files/css/modern.min.css" rel="stylesheet" type="text/css"/>
    <link href="/app/files/css/themes/white.css" class="theme-color" rel="stylesheet" type="text/css"/>
    <link href="/app/files/css/custom.css" rel="stylesheet" type="text/css"/>

</head>
<body class="page-error">
<main class="page-content">
    <div class="page-inner">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-4 center">
                    <h1 class="text-xxl text-primary text-center">404</h1>
                    <div class="details">
                        <h3>Vex - Sistema de vendas externas!</h3>
                        <p>A página que você tentou acessar não existe.</p>
                        <p class="f-bold">WebDatasoft.com.br</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
</body>
</html>


